name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEPLOYMENT_ZIP: quakeone-servers-app.zip
  DEPLOYMENT_BUCKET: us-east-1-quakeone-deployments
  ARTIFACTS_BUCKET: us-east-2-quakeone-servers
  ARTIFACTS_BUCKET_REGION: us-east-2
  AWS_REGION: us-east-1
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:fermium

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          apt-get update
          apt-get -y install zip unzip
          npm --unsafe-perm install
          npm run build
          mkdir artifacts
          cd dist; cp -r . ../artifacts; cd ../

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deployable
          path: artifacts/
  # This workflow contains a single job called "build"
  publish:
    if: github.ref == 'refs/heads/main'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download artifacts from build
        uses: actions/download-artifact@v2
        with:
          name: deployable
          path: artifacts/

      - name: Upload artifacts to S3 bucket
        run: aws s3 sync artifacts s3://${{ env.ARTIFACTS_BUCKET }} --region ${{ env.ARTIFACTS_BUCKET_REGION }} --delete
